on:
  workflow_dispatch:
    inputs:
      source_code:
          description: 'Source code URL'     
          required: true
      commit_hash:
          description: 'Commit Hash'     
          required: false
      device:
        description: 'Select device'     
        required: true
        type: choice
        options:
        - AX1800
        - AXT1800
        - MT2500
        - MT3000
        - SF1200
        - SFT1200

jobs:
  setpackage:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: build ipk
      id: build
      env:
        SOURCECODEURL: ${{ github.event.inputs.source_code }}
        COMMITHASH: ${{ github.event.inputs.commit_hash }}
        BOARD: ${{ github.event.inputs.device }}
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./build_otbr.sh
        ./build_otbr.sh
    - uses: actions/upload-artifact@master
      with:
        name: openthread_br_related_ipks
        path: |
          ./*ipk*
